# hugo.toml - Core configuration for the site builder
#
# Only add settings here that *never* changes.
#
# For site-specific settings, use hugo.site.toml.
# For variant-specific settings, use config.<variant>.toml.

languageCode = 'en-us'
theme = 'union'
disableKinds = ["RSS"]

# Enable sitemap generation
[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[params]
_merge = "deep"
show_inactive = false
highlight_active = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

#----------------------------------------------------------
# Search

[params.search]
app_id = "ZK72K15QRI"
search_key = "59e5451a3db8540ee70dc8dd04fe6287"
index_name = "union"
