# hugo.toml - Core configuration for the site builder
#
# Only add settings here that *never* changes.
#
# For site-specific settings, use hugo.site.toml.
# For variant-specific settings, use config.<variant>.toml.

languageCode = 'en-us'
disableKinds = ["RSS"]
enableRobotsTXT = true
enableEmoji = true

# Enable sitemap generation
[outputs]
  # 'home': The main site homepage. 'HTML' for the page, 'RSS' for feed readers.
  home = ["HTML", "RSS"]

  # 'page': Individual content pages. 'HTML' for the page, 'MD' for markdown processing.
  page = ["HTML", "MD"]

  # 'section': Top-level content sections (e.g., docs, tutorials). 'HTML' for rendering, 'RSS' for section-specific feeds, 'MD' for markdown processing.
  section = ["HTML", "RSS", "MD"]

  # 'taxonomy': Used for tag/category listing pages. 'HTML' for rendering, 'RSS' for taxonomy feeds.
  taxonomy = ["HTML", "RSS"]

  # 'robotsTXT': Generate robots.txt file for search engine crawling
  robotsTXT = ["ROBOTS"]

[outputFormats]
  [outputFormats.MD]
    mediaType = "text/plain"
    baseName = "index"
    path = "tmp-md"
    isPlainText = true

[params]
_merge = "deep"
show_inactive = false
highlight_active = false

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

#----------------------------------------------------------
# Search

[params.search]
app_id = "ZK72K15QRI"
search_key = "59e5451a3db8540ee70dc8dd04fe6287"
index_name = "union"
