# hugo.site.toml - Configurations for the site content
#
# ** DO NOT OVERRIDE ANY SETTING FROM hugo.toml. IT WILL NOT WORK **
#
# Also, do *not* introduce new variables here without a counterpart in
# hugo.toml, to avoid conflicts with future builds.
#
#   An exception to this rule is to add new values to maps, such as keys.
#
#   In other words, introducing a new [params.xxx] is a no-no, but
#   [params.yyy.zzz] whenever yyy exists is okay to add new zzz.

title = 'Union.ai Docs'

[params]
_merge = "deep"
signup_link = "https://www.union.ai/pricing"

custom_css = [
  "404.css",
  "api.css",
  "base.css",
  "breadcrumb.css",
  "card.css",
  "codeblock.css",
  "footer.css",
  "header.css",
  "images.css",
  "key.css",
  "markdown.css",
  "mermaid.css",
  "plugin.css",
  "search.css",
  "sidebar.css",
  "tabs.css",
  "toc.css",
]
custom_js = [
  "key.js",
  "sidebar.js",
  "theme.js",
  "tags.js",
]

[params.variant_weights]
flyte = 1
serverless = 4
byoc = 2
selfmanaged = 3

#----------------------------------------------------------
# Keywords

#
# Used by {{< key >}} shortcode. Please refer to SHORTCODES.md (key section)
# for documentation.
#
# ===== IMPORTANT =====
#
# DO NOT add new keys here without, in the same PR, adding them to the
# documentation above as well.
#
[params.key]

[params.key.default_project]
flyte = "flytesnacks"
serverless = "default"
byoc = "flytesnacks"
selfmanaged = "flytesnacks"

[params.key.product_full_name]
flyte = "Flyte OSS"
serverless = "Union.ai Serverless"
byoc = "Union.ai BYOC"
selfmanaged = "Union.ai Self-managed"

[params.key.product_name]
flyte = "Flyte"
serverless = "Union.ai"
byoc = "Union.ai"
selfmanaged = "Union.ai"

[params.key.product]
flyte = "flyte"
serverless = "union"
byoc = "union"
selfmanaged = "union"

[params.key.kit_name]
flyte = "Flytekit"
serverless = "Union"
byoc = "Union"
selfmanaged = "Union"

[params.key.kit]
flyte = "flytekit"
serverless = "union"
byoc = "union"
selfmanaged = "union"

[params.key.kit_as]
flyte = "fl"
serverless = "union"
byoc = "union"
selfmanaged = "union"

[params.key.kit_import]
flyte = "flytekit as fl"
serverless = "union"
byoc = "union"
selfmanaged = "union"

[params.key.kit_remote]
flyte = "FlyteRemote"
serverless = "UnionRemote"
byoc = "UnionRemote"
selfmanaged = "UnionRemote"

[params.key.cli_name]
flyte = "Pyflyte"
serverless = "Union"
byoc = "Union"
selfmanaged = "Union"

[params.key.cli]
flyte = "pyflyte"
serverless = "union"
byoc = "union"
selfmanaged = "union"

[params.key.ctl_name]
flyte = "Flytectl"
serverless = "Uctl"
byoc = "Uctl"
selfmanaged = "Uctl"

[params.key.ctl]
flyte = "flytectl"
serverless = "uctl"
byoc = "uctl"
selfmanaged = "uctl"

[params.key.config_env]
flyte = "FLYTECTL_CONFIG"
serverless = "UNION_CONFIG"
byoc = "UNION_CONFIG"
selfmanaged = "UNION_CONFIG"

[params.key.env_prefix]
flyte = "FLYTE"
serverless = "UNION"
byoc = "UNION"
selfmanaged = "UNION"

[params.key.docs_home]
flyte = "https://www.union.ai/docs/flyte"
serverless = "https://www.union.ai/docs/serverless"
byoc = "https://www.union.ai/docs/byoc"
selfmanaged = "https://www.union.ai/docs/selfmanaged"

[params.key.map_func]
flyte = "map_task"
serverless = "map"
byoc = "map"
selfmanaged = "map"

[params.key.logo]
flyte = "icon-logo-flyte.png"
serverless = "icon-logo.svg"
byoc = "icon-logo.svg"
selfmanaged = "icon-logo.svg"

[params.key.favicon]
flyte = "icon-logo-flyte.png"
serverless = "favicon.ico"
byoc = "favicon.ico"
selfmanaged = "favicon.ico"

# Plase DO NOT add new keys without documenting them the contributing guide in the same PR.
